****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
* Date:                 Mon Dec 18 11:02:12 CET 2023
* Job name:             sampling
* Job id:               58381390
* User:                 tlaclave
* Account:              qubic
* Submit host:          cca001
* Partition:            hpc
* Quality of service:   normal
* Nodelist:             ccwpslurm0001
****************************************************************
Chosen method = MCMC
{'Method': 'FMM', 'Sky': {'CMB': {'cmb': True, 'r': [0, 'f', 'r', 0.001], 'Alens': [1, 'f', 'A_{lens}', 1]}, 'Foregrounds': {'Dust': True, 'nu0_d': 353, 'Ad': [4, 'nf', 'A_d', 4], 'betad': [1.54, 'nf', '\\beta_d', 1.54], 'alphad': [-0.4, 'nf', '\\alpha_d', -0.4], 'deltad': [1, 'nf', '\\Delta_d', 1], 'Synchrotron': False, 'nu0_s': 23, 'As': [0, 'nf', 'A_s', 0], 'betas': [-3, 'nf', '\\beta_s', -3], 'alphas': [-0.4, 'nf', '\\alpha_s', -0.4], 'deltas': [1, 'nf', '\\Delta_s', 1], 'DustSync': False, 'eps': [0, 'nf', '\\varepsilon', 0]}, 'nside': 256}, 'QUBIC': {'method': 'MM', 'randomreal': True, 'npointings': 8000, 'nsub': 8, 'nrec': 2, 'seed': 0, 'iteration': 1, 'ndet': 1, 'npho150': 1, 'npho220': 1, 'synthbeam_kmax': 1, 'detector_nep': 4.7e-17, 'nhwp_angles': 3, 'dtheta': 15, 'type': 'wide', 'covcut': 0.2, 'kappa': 0, 'convolution': False, 'bandpass_correction': True, 'RA_center': 0, 'DEC_center': -57, 'dust_model': 'd0', 'sync_model': 's0', 'fsky': 0.035}, 'Spectrum': {'do_spectrum': True, 'method': 'namaster', 'dl': 30, 'lmin': 40, 'aposize': 10, 'beam_correction': False, 'pixwin_correction': False, 'noise_correction': False, 'nbins': 10}, 'PCG': {'maxiter': 300, 'tol': 1e-20, 'gif': False}, 'Sampler': {'do_sampler': False, 'nsteps': 200, 'N': 5, 'ndim': 2, 'discard': 100, 'markers': False, 'sig_initial_guess': 0.01, 'title_limit': 1}, 'Data': {'datafilename': 'MC', 'planck': {'30GHz': False, '44GHz': False, '70GHz': False, '100GHz': False, '143GHz': False, '217GHz': False, '353GHz': False}, 'level_planck_noise': 0, 'use_external_data': False}}
emcee: Exception while calling your likelihood function:
  params: [ 0.73214708  6.85571885 -3.55928003]
  args: []
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/site-packages/emcee/ensemble.py", line 545, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "sampling.py", line 650, in chi2
    return self.prior(tab) - 0.5 * np.sum(((self.mean_ps_sky - (CMB(self.ell).model_cmb(r, Alens) + Dust(self.ell).model_dust(Ad, alphad, betad, deltad, nu0_d)))/(self.error_ps_noise))**2)
  File "sampling.py", line 480, in __init__
    realisation = DataFMM().find_data()
NameError: name 'DataFMM' is not defined
emcee: Exception while calling your likelihood function:
  params: [0.67363651 7.78716543 7.28958681]
  args: []
  kwargs: {}
  exception:
emcee: Exception while calling your likelihood function:
  params: [0.47290926 9.64788239 5.20414431]
  args: []
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/site-packages/emcee/ensemble.py", line 545, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "sampling.py", line 650, in chi2
    return self.prior(tab) - 0.5 * np.sum(((self.mean_ps_sky - (CMB(self.ell).model_cmb(r, Alens) + Dust(self.ell).model_dust(Ad, alphad, betad, deltad, nu0_d)))/(self.error_ps_noise))**2)
  File "sampling.py", line 480, in __init__
    realisation = DataFMM().find_data()
NameError: name 'DataFMM' is not defined
emcee: Exception while calling your likelihood function:
  params: [0.65083521 7.14824929 8.88345007]
  args: []
  kwargs: {}
  exception:
emcee: Exception while calling your likelihood function:
  params: [ 0.96131657 -2.23480484 -0.69808681]
  args: []
  kwargs: {}
  exception:
emcee: Exception while calling your likelihemcee: Exception while calling your likelihood function:
  params: [0.60800671 8.78483866 0.7815124 ]
  args: []
  kwargs: {}
  exception:
emcee: Exception while calling your likelihood function:
  params: [0.19560022 4.99090769 5.28921049]
  args: []
  kwargs: {}
  exception:
emcee: Exception while calling your likelihood function:
  params: [  0.46646613 -14.91261801  -2.30989101]
  args: []
  kwargs: {}
  exception:
emcee: Exception while calling your likelihood function:
  params: [ 0.17450516 12.8154529  -0.31299329]
  args: []
  kwargs: {}
  exception:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/site-packages/emcee/ensemble.py", line 545, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "sampling.py", line 650, in chi2
    return self.prior(tab) - 0.5 * np.sum(((self.mean_ps_sky - (CMB(self.ell).model_cmb(r, Alens) + Dust(self.ell).model_dust(Ad, alphad, betad, deltad, nu0_d)))/(self.error_ps_noise))**2)
  File "sampling.py", line 480, in __init__
    realisation = DataFMM().find_data()
NameError: name 'DataFMM' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sampling.py", line 868, in <module>
    MCMC()()
  File "sampling.py", line 668, in __call__
    sampler.run_mcmc(p0, mcmc_steps, progress=True)
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/site-packages/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/site-packages/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/site-packages/emcee/ensemble.py", line 427, in compute_log_prob
    map_func(self.log_prob_fn, (p[i] for i in range(len(p))))
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/pbs/throng/qubic/Anaconda3/envs/qubic_python38/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
NameError: name 'DataFMM' is not defined
****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
Date: Mon Dec 18 11:02:17 CET 2023
Job informations can be found using these commands:
Accounting:
sacct -j 58381390
Efficiency:
seff 58381390
****************************************************************
